kiosk = {
			[2] = "DK",
			[3] = "Diddy",
			[4] = "Lanky",
			[5] = "Tiny",
			[6] = "Chunky",
			[7] = "Rambi",

			--[9] = "Unknown", -- Always loaded -- TODO: Figure out what actors 9-14 do
			--[10] = "Unknown", -- Always loaded -- What is this?
			[11] = "Loading Zone Controller", -- Always loaded
			[12] = "Object Model 2 Controller", -- Always loaded
			--[13] = "Unknown", -- Always loaded -- What is this?
			--[14] = "Unknown", -- Always loaded -- What is this?
			[16] = "Cannon Barrel",
			[17] = "Rambi Crate",
			[18] = "Barrel",
			[20] = "Pushable Box", -- Unused
			[21] = "Barrel Spawner",
			[22] = "Cannon",
			[23] = "Race Checkpoint", -- Circular
			[24] = "Hunky Chunky Barrel",
			[25] = "TNT Barrel",
			[26] = "TNT Barrel Spawner (Army Dillo)",
			[27] = "Bonus Barrel",
			[29] = "Fireball", -- Army Dillo, Dogadon
			[30] = "Bridge", -- Creepy Castle?
			[31] = "Swinging Light", -- Grey
			[32] = "Vine", -- Brown

			[35] = "Peanut", -- Projectile
			[37] = "Pineapple", -- Projectile
			[38] = "Large Bridge", -- Unused?
			[39] = "Mini Monkey Barrel",
			[40] = "Orange",
			[41] = "Grape", -- Projectile
			[42] = "Feather", -- Projectile
			[43] = "Laser",
			[44] = "Golden Banana", -- Held by Vulture
			--[45] = "Unknown", -- Crash
			[46] = "Watermelon Slice",
			[47] = "Coconut", -- Projectile
			[48] = "Rocketbarrel",
			[49] = "Orange/Lime", -- TODO: Not sure which
			[50] = "Ammo Crate", -- Unusued? Normally these are object model 2
			[51] = "Orange", -- Unusued? Normally these are object model 2
			[52] = "Banana Coin", -- Unusued? Normally these are object model 2
			[53] = "DK Coin", -- Unusued? Normally these are object model 2

			[55] = "Orangstand Sprint Barrel",
			[56] = "Strong Kong Barrel",
			[57] = "Swinging Light", -- Green

			[60] = "Boulder",

			[62] = "Vase (O)",
			[63] = "Vase (:)",
			[64] = "Vase (Triangle)",
			[65] = "Vase (+)",
			[66] = "Cannon Ball", -- Fungi Minigame
			[68] = "Vine", -- Green
			[69] = "Counter", -- Unused?

			[71] = "Boss Key",
			[72] = "Cannon", -- Fungi Minigame

			[74] = "Blueprint (Diddy)",
			[75] = "Blueprint (Chunky)",
			[76] = "Blueprint (Lanky)",
			[77] = "Blueprint (DK)",
			[78] = "Blueprint (Tiny)",
			--[79] = "Unknown", -- Crash
			[81] = "Boulder", -- Unused
			[82] = "Spider Web",
			[83] = "Steel Keg Spawner",
			[84] = "Steel Keg", -- Looks different from retail
			[85] = "Collectable", -- Not sure what yet
			--[86] = "Unknown", -- Crash
			[88] = "Missile?",

			[90] = "Balloon (Diddy)",
			[91] = "Stalactite",
			[93] = "Car",
			[95] = "Hunky Chunky Barrel",
			[96] = "TNT Barrel Spawner (Dogadon)",
			[97] = "Tag Barrel",

			[99] = "1 Pad",
			[100] = "2 Pad",
			[101] = "3 Pad",
			[102] = "4 Pad",
			[103] = "5 Pad",
			[104] = "6 Pad",
			[106] = "Lever", -- Gorilla Grab
			[109] = "CB Bunch", -- Unusued? Normally these are object model 2
			[110] = "Balloon (Chunky)",
			[111] = "Balloon (Tiny)",
			[112] = "Balloon (Lanky)",
			[113] = "Balloon (DK)",
			[114] = "Padlock", -- K. Lumsy
			[127] = "Headphones",
			[128] = "Enguarde Crate",
			[134] = "Kaboom",
			[137] = "Beaver",
			[139] = "Krash",
			[140] = "Book",
			[141] = "Jack in the Box (Beta)",
			[142] = "Klobber",
			[143] = "Zinger",
			[144] = "Snide",
			[145] = "Army Dillo",
			[147] = "Klump",
			[148] = "Armadillo (Beta)",
			[149] = "Camera",
			[150] = "Cranky",
			[151] = "Funky",
			[152] = "Candy",
			[153] = "Beetle",
			[154] = "Mermaid",
			[155] = "Vulture",
			[156] = "Squawks",
			[157] = "Cutscene DK",
			[158] = "Cutscene Diddy",
			[159] = "Cutscene Lanky",
			[160] = "Cutscene Tiny",
			[161] = "Cutscene Chunky",
			[162] = "Llama",
			[165] = "Mad Jack",
			[164] = "Padlock & Key",
			[166] = "Klaptrap", -- Green
			[167] = "Zinger",
			[168] = "Vulture",
			[169] = "Klaptrap (Purple)",
			[170] = "Klaptrap (Red)",
			[173] = "Rareware Logo",
			[174] = "Orange Kremling (Beta)",
			[175] = "Rareware Logo",
			[177] = "Minecart (TNT)",
			[178] = "Minecart (TNT)",
			[179] = "Pufftoss",
			[184] = "Rareware Logo",
			[185] = "Rareware Logo",
			[187] = "Boxing Glove in the Box (Beta)",
			[188] = "Mushroom Man",
			[189] = "Rareware Logo",
			[190] = "Troff",
			[191] = "Rareware Logo",
			[193] = "Rareware Logo",
			[194] = "Rareware Logo",
			[195] = "Ruler",
			[196] = "Toy Box",
			[198] = "Squawks",
			[199] = "Scoff",
			[200] = "Robo-Kremling",
			[201] = "Dogadon",
			[202] = "Bug (Beta)",
			[204] = "Kremling",
			[206] = "Spotlight Fish",
			[207] = "Kasplat (DK)",
			[208] = "Kasplat (Diddy)",
			[209] = "Kasplat (Lanky)",
			[210] = "Kasplat (Tiny)",
			[211] = "Kasplat (Chunky)",
			[212] = "Mechanical Fish",
			[213] = "Seal",
			[214] = "Banana Fairy",
			[215] = "Squawks",
			[216] = "Zinger",
			[217] = "Owl",
			[219] = "Rabbit",
			[220] = "Nintendo Logo",
			[222] = "Shockwave",
			[221] = "Cutscene Object", -- Fake Chunky in Dogadon 2 opening cutscene
			[226] = "Guard", -- Stealthy Snoop
			[228] = "Robo-Zinger",
			[229] = "Krossbones",
			[230] = "Fireball Shockwave", -- Dogadon
			[232] = "Light Beam", -- Boss fights etc
			[234] = "Shuri",
			[235] = "Gimpfish",
			[236] = "Mr. Dice",
			[237] = "Sir Domino",
			[238] = "Mr. Dice",
			[239] = "Rabbit",
			[240] = "Beaver",
			[241] = "Fireball (With Glasses)", -- From Chunky 5DI
			[243] = "K. Lumsy",
			[245] = "Squawks",
			[249] = "K. Rool",
			[251] = "Skeleton Head",
			[253] = "Bat",
			[254] = "Giant Clam",
			[256] = "Tomato",
			[257] = "Kritter-in-a-Sheet",
			[258] = "Pufftup",
			[266] = "Enemy Car",
			[271] = "Seal",
			[272] = "Kong Logo (Instrument)",
			[273] = "Spotlight",
			[275] = "Minecart (TNT)",
			[276] = "Idle Particle",
			[279] = "Rareware Logo",
			[281] = "Kong (Tag Barrel)",
			[282] = "Locked Kong (Tag Barrel)",
};
final = {
[2] = "DK",
		[3] = "Diddy",
		[4] = "Lanky",
		[5] = "Tiny",
		[6] = "Chunky",
		[7] = "Krusha",
		[8] = "Rambi",
		[9] = "Enguarde",
		--[10] = "Unknown", -- Always loaded -- TODO: Figure out what actors 10-15 do
		--[11] = "Unknown", -- Always loaded -- What is this?
		[12] = "Loading Zone Controller", -- Always loaded
		[13] = "Object Model 2 Controller", -- Always loaded
		--[14] = "Unknown", -- Always loaded -- What is this?
		--[15] = "Unknown", -- Always loaded -- What is this?
		[17] = "Cannon Barrel",
		[18] = "Rambi Crate",
		[19] = "Barrel (Diddy 5DI)",
		[20] = "Camera Focus Point", -- Exists during some cutscenes
		[21] = "Pushable Box",
		[22] = "Barrel Spawner", -- Normal barrel on a star pad, unused?
		[23] = "Cannon",
		[25] = "Hunky Chunky Barrel",
		[26] = "TNT Barrel",
		[27] = "TNT Barrel Spawner", -- Army Dillo
		[28] = "Bonus Barrel",
		[29] = "Minecart",
		[30] = "Fireball", -- Boss fights
		[31] = "Bridge (Castle)",
		[32] = "Swinging Light",
		[33] = "Vine", -- Brown
		[34] = "Kremling Kosh Controller",
		[35] = "Melon (Projectile)",
		[36] = "Peanut",
		[37] = "Rocketbarrel", -- On Kong
		[38] = "Pineapple",
		[39] = "Large Brown Bridge", -- Unused?
		[40] = "Mini Monkey Barrel",
		[41] = "Orange",
		[42] = "Grape",
		[43] = "Feather",
		[44] = "Laser", -- Projectile
		[45] = "Golden Banana", -- Vulture, bonus barrels (US code 0x6818EE), probably some other places
		[46] = "Barrel Gun", -- Teetering Turtle Trouble
		[47] = "Watermelon Slice",
		[48] = "Coconut",
		[49] = "Rocketbarrel", -- The Barrel
		[50] = "Lime",
		[51] = "Ammo Crate", -- Dropped by Red Klaptrap
		[52] = "Orange Pickup", -- Dropped by Klump & Purple Klaptrap
		[53] = "Banana Coin", -- Dropped by "Diddy", otherwise unused?
		[54] = "DK Coin", -- Minecart
		[55] = "Small Explosion", -- Seasick Chunky
		[56] = "Orangstand Sprint Barrel",
		[57] = "Strong Kong Barrel",
		[58] = "Swinging Light",
		[59] = "Fireball", -- Mad Jack etc.
		[60] = "Bananaporter",
		[61] = "Boulder",
		[62] = "Minecart", -- DK?
		[63] = "Vase (O)",
		[64] = "Vase (:)",
		[65] = "Vase (Triangle)",
		[66] = "Vase (+)",
		[67] = "Cannon Ball",
		-- [68] = "Unknown",
		[69] = "Vine", -- Green
		[70] = "Counter", -- Unused?
		[71] = "Kremling (Red)", -- Lanky's Keyboard Game in R&D
		[72] = "Boss Key",
		[73] = "Cannon", -- Galleon Minigame
		[74] = "Cannon Ball", -- Galleon Minigame Projectile
		[75] = "Blueprint (Diddy)",
		[76] = "Blueprint (Chunky)",
		[77] = "Blueprint (Lanky)",
		[78] = "Blueprint (DK)",
		[79] = "Blueprint (Tiny)",
		[80] = "Minecart", -- Chunky?
		[81] = "Fire Spawner? (Dogadon)", -- TODO: Verify
		[82] = "Boulder Debris", -- Minecart
		[83] = "Spider Web", -- Fungi miniBoss
		[84] = "Steel Keg Spawner",
		[85] = "Steel Keg",
		[86] = "Crown",
		[87] = "Minecart", -- BONUS
		-- [88] = "Unknown",
		[89] = "Fire", -- Unused?
		[90] = "Ice Wall?",
		[91] = "Balloon (Diddy)",
		[92] = "Stalactite",
		[93] = "Rock Debris", -- Rotating, Unused?
		[94] = "Car", -- Unused?
		[95] = "Pause Menu",
		[96] = "Hunky Chunky Barrel (Dogadon)",
		[97] = "TNT Barrel Spawner (Dogadon)",
		[98] = "Tag Barrel",
		[99] = "Fireball", -- Get Out
		[100] = "1 Pad (Diddy 5DI)",
		[101] = "2 Pad (Diddy 5DI)",
		[102] = "3 Pad (Diddy 5DI)",
		[103] = "4 Pad (Diddy 5DI)",
		[104] = "5 Pad (Diddy 5DI)",
		[105] = "6 Pad (Diddy 5DI)",
		[106] = "Kong Reflection",
		[107] = "Bonus Barrel (Hideout Helm)",
		-- [108] = "Unknown",
		[109] = "Race Checkpoint",
		[110] = "CB Bunch", -- Unused? Doesn't seem to work, these are normally model 2
		[111] = "Balloon (Chunky)",
		[112] = "Balloon (Tiny)",
		[113] = "Balloon (Lanky)",
		[114] = "Balloon (DK)",
		[115] = "K. Lumsy's Cage", -- TODO: Also rabbit race finish line?
		[116] = "Chain",
		[117] = "Beanstalk",
		[118] = "Yellow ?", -- Unused?
		[119] = "CB Single (Blue)", -- Unused? Doesn't seem to work, these are normally model 2
		[120] = "CB Single (Yellow)", -- Unused? Doesn't seem to work, these are normally model 2
		[121] = "Crystal Coconut", -- Unused? Doesn't seem to work, these are normally model 2
		[122] = "DK Coin", -- Multiplayer
		[123] = "Kong Mirror", -- Creepy Castle Museum
		[124] = "Barrel Gun", -- Peril Path Panic
		[125] = "Barrel Gun", -- Krazy Kong Klamour
		[126] = "Fly Swatter",
		[127] = "Searchlight", -- Searchlight Seek
		[128] = "Headphones",
		[129] = "Enguarde Crate",
		[130] = "Apple", -- Fungi
		[131] = "Worm", -- Fungi
		[132] = "Enguarde Crate (Unused?)",
		[133] = "Barrel",
		[134] = "Training Barrel",
		[135] = "Boombox", -- Treehouse
		[136] = "Tag Barrel",
		[137] = "Tag Barrel", -- Troff'n'Scoff
		[138] = "B. Locker",
		[139] = "Rainbow Coin Patch",
		[140] = "Rainbow Coin",
		-- [141] = "Unknown",
		-- [142] = "Unknown",
		-- [143] = "Unknown",
		-- [144] = "Unknown",
		[145] = "Cannon (Seasick Chunky)", -- Internal name "Puffer cannon"
		-- [146] = "Unknown",
		[147] = "Balloon (Unused - K. Rool)", -- Internal Name: K. Rool Banana Balloon, unsure of purpose. Can only be popped by Lanky
		[148] = "Rope", -- K. Rool's Arena
		[149] = "Banana Barrel", -- Lanky Phase
		[150] = "Banana Barrel Spawner", -- Lanky Phase, internal name "Skin barrel generator"
		-- [151] = "Unknown",
		-- [152] = "Unknown",
		-- [153] = "Unknown",
		-- [154] = "Unknown",
		-- [155] = "Unknown",
		[156] = "Wrinkly",
		-- [157] = "Unknown",
		-- [158] = "Unknown",
		-- [159] = "Unknown",
		-- [160] = "Unknown",
		-- [161] = "Unknown",
		-- [162] = "Unknown",
		[163] = "Banana Fairy (BFI)",
		[164] = "Ice Tomato",
		[165] = "Tag Barrel (King Kut Out)",
		[166] = "King Kut Out Part",
		[167] = "Cannon",
		-- [168] = "Unknown",
		[169] = "Pufftup", -- Pufftoss Fight
		[170] = "Damage Source", -- K. Rool's Glove
		[171] = "Orange", -- Krusha's Gun
		[173] = "Cutscene Controller",
		-- [174] = "Unknown",
		[175] = "Kaboom",
		[176] = "Timer",
		[177] = "Timer Controller", -- Pufftoss Fight & Fac Beaver Bother Spawn Timer
		[178] = "Beaver", -- Blue
		[179] = "Shockwave (Mad Jack)",
		[180] = "Krash", -- Minecart Club Guy
		[181] = "Book", -- Castle Library
		[182] = "Klobber",
		[183] = "Zinger",
		[184] = "Snide",
		[185] = "Army Dillo",
		[186] = "Kremling", -- Kremling Kosh
		[187] = "Klump",
		[188] = "Camera",
		[189] = "Cranky",
		[190] = "Funky",
		[191] = "Candy",
		[192] = "Beetle", -- Race
		[193] = "Mermaid",
		[194] = "Vulture",
		[195] = "Squawks",
		[196] = "Cutscene DK",
		[197] = "Cutscene Diddy",
		[198] = "Cutscene Lanky",
		[199] = "Cutscene Tiny",
		[200] = "Cutscene Chunky",
		[201] = "Llama",
		[202] = "Fairy Picture",
		[203] = "Padlock (T&S)",
		[204] = "Mad Jack",
		[205] = "Klaptrap", -- Green
		[206] = "Zinger",
		[207] = "Vulture (Race)",
		[208] = "Klaptrap (Purple)",
		[209] = "Klaptrap (Red)",
		[210] = "GETOUT Controller",
		[211] = "Klaptrap (Skeleton)",
		[212] = "Beaver (Gold)",
		[213] = "Fire Column Spawner", -- Japes Minecart
		[214] = "Minecart (TNT)", -- Minecart Mayhem
		[215] = "Minecart (TNT)",
		[216] = "Pufftoss",
		-- [217] = "Unknown",
		[218] = "Handle",
		[219] = "Slot",
		[220] = "Cannon (Seasick Chunky)",
		[221] = "Light Piece", -- Lanky Phase
		[222] = "Banana Peel", -- Lanky Phase
		[223] = "Fireball Spawner", -- Factory Crusher Room
		[224] = "Mushroom Man",
		-- [225] = "Unknown",
		[226] = "Troff",
		[227] = "K. Rool's Foot",
		[228] = "Bad Hit Detection Man",
		-- [229] = "Unknown",
		[230] = "Ruler",
		[231] = "Toy Box",
		[232] = "Text Overlay",
		[233] = "Squawks",
		[234] = "Scoff",
		[235] = "Robo-Kremling",
		[236] = "Dogadon",
		-- [237] = "Unknown",
		[238] = "Kremling",
		[239] = "Bongos",
		[240] = "Spotlight Fish",
		[241] = "Kasplat (DK)",
		[242] = "Kasplat (Diddy)",
		[243] = "Kasplat (Lanky)",
		[244] = "Kasplat (Tiny)",
		[245] = "Kasplat (Chunky)",
		[246] = "Mechanical Fish",
		[247] = "Seal",
		[248] = "Banana Fairy",
		[249] = "Squawks with spotlight",
		[250] = "Owl",
		[251] = "Spider miniBoss",
		[252] = "Rabbit", -- Fungi
		[253] = "Nintendo Logo",
		[254] = "Cutscene Object", -- For objects animated by Cutscenes
		[255] = "Shockwave",
		[256] = "Minigame Controller",
		[257] = "Fire Breath Spawner", -- Aztec Beetle Race
		[258] = "Shockwave", -- Boss
		[259] = "Guard", -- Stealthy Snoop
		[260] = "Text Overlay", -- K. Rool fight
		[261] = "Robo-Zinger",
		[262] = "Krossbones",
		[263] = "Fire Shockwave (Dogadon)",
		[264] = "Squawks",
		[265] = "Light beam", -- Boss fights etc
		[266] = "DK Rap Controller", -- Handles the lyrics etc
		[267] = "Shuri",
		[268] = "Gimpfish",
		[269] = "Mr. Dice",
		[270] = "Sir Domino",
		[271] = "Mr. Dice",
		[272] = "Rabbit",
		[273] = "Fireball (With Glasses)", -- From Chunky 5DI
		-- [274] = "Unknown",
		[275] = "K. Lumsy",
		[276] = "Spiderling",
		[277] = "Squawks",
		[278] = "Projectile", -- Spider miniBoss
		-- [279] = "Unknown",
		[280] = "Spider Silk String", -- Spider miniBoss
		[281] = "K. Rool (DK Phase)",
		[282] = "Retexturing Controller", -- Beaver Bother
		[283] = "Skeleton Head",
		-- [284] = "Unknown",
		[285] = "Bat",
		[286] = "Giant Clam",
		-- [287] = "Unknown",
		[288] = "Tomato", -- Fungi
		[289] = "Kritter-in-a-Sheet",
		[290] = "Pufftup",
		[291] = "Kosha",
		[292] = "K. Rool (Diddy Phase)",
		[293] = "K. Rool (Lanky Phase)",
		[294] = "K. Rool (Tiny Phase)",
		[295] = "K. Rool (Chunky Phase)",
		-- [296] = "Unknown",
		[297] = "Battle Crown Controller",
		-- [298] = "Unknown",
		-- [299] = "Unknown",
		[299] = "Textbox",
		[300] = "Snake", -- Teetering Turtle Trouble
		[301] = "Turtle", -- Teetering Turtle Trouble
		[302] = "Toy Car", -- Player in the Factory Toy Car Race
		[303] = "Toy Car",
		[304] = "Camera", -- Factory Toy Car Race
		[305] = "Missile", -- Car Race
		-- [306] = "Unknown",
		-- [307] = "Unknown",
		[308] = "Seal",
		[309] = "Kong Logo (Instrument)", -- DK for DK, Star for Diddy, DK for Lanky, Flower for Tiny, DK for Chunky
		[310] = "Spotlight", -- Tag barrel, instrument etc.
		[311] = "Race Checkpoint", -- Seal race & Castle car race
		[312] = "Minecart (TNT)",
		[313] = "Idle Particle",
		[314] = "Rareware Logo",
		-- [315] = "Unknown",
		[316] = "Kong (Tag Barrel)",
		[317] = "Locked Kong (Tag Barrel)",
		-- [318] = "Unknown",
		[319] = "Propeller (Boat)",
		[320] = "Potion", -- Cranky Purchase
		[321] = "Fairy (Refill)", -- Refill Fairy
		[322] = "Car", -- Car Race
		[323] = "Enemy Car", -- Car Race, aka George
		[324] = "Text Overlay Controller", -- Candy's
		[325] = "Shockwave", -- Simian Slam
		[326] = "Main Menu Controller",
		[327] = "Kong", -- Krazy Kong Klamour
		[328] = "Klaptrap", -- Peril Path Panic
		[329] = "Fairy", -- Peril Path Panic
		[330] = "Bug", -- Big Bug Bash
		[331] = "Klaptrap", -- Searchlight Seek
		[332] = "Big Bug Bash Controller?", -- TODO: Fly swatter?
		[333] = "Barrel (Main Menu)",
		[334] = "Padlock (K. Lumsy)",
		[335] = "Snide's Menu",
		[336] = "Training Barrel Controller",
		[337] = "Multiplayer Model (Main Menu)",
		[338] = "End Sequence Controller",
		[339] = "Arena Controller", -- Rambi/Enguarde
		[340] = "Bug", -- Trash Can
		[342] = "Try Again Dialog",
		[343] = "Pause Menu", -- Mystery menu bosses
};

for i = 0, 343 do
	kiosk_name = kiosk[i];
	final_name = final[i];
	if kiosk_name == nil then
		kiosk_name == "?";
	end
	if final_name == nil then
		final_name == "?";
	end
	print("["..i.."], Final: "..final_name..", Kiosk: "..kiosk_name);
end