strings = {
"iyppeeee!eb liylt ehi ech sar\nceieev!db liyl",
"iyppeeee!eb\nliylg toa  nci-ercae!mb\nliylg t",
" Imah re eof r aahdno  fht eci\neeho ev!rH re",
"nI\tm'h re eof rnai ecc-ermah\nna dtio ev!r ",
"aWaaaa!hr qeiuerb liylt ehi\nec.. .eruqri eib",
"!aWaaaa!hb\nliylw na tci-ercae.m..b\nliylw na",
"hT eohrrro..\n.ht eohrrro.. ",
"hT eohrrro..\n.ht eohrrro.. ",
"H\nuo romoovo eott eho tuised\n! ",
"H\nuo romoovo eott eho tuised\n! ",
"hTre'e sht exertcaitnop iotn\n.oN,wm ooooevo ",
"!nUsuau loj!bT eh yahevg iaen\ndhtsi ,osdlei.",
"uOstatdnni gowkr\n!oY'ueve raen dhtsi ,osdlei",
"!aCrboiel tfop sotioi nniy uot\nehl raav !oRs",
"oMevi  toy uowtrlhse samggto\n!oRsa thttab ri",
"eH,yc ulkco  faCvlni !hT\neafrbcio  fiNec ,ht",
"eH,yC laiv nlccu!kN\nci eafrbci\n,hTsig yus'g",
"\nhT eocolen law sneorlldea dnl\naoed duo rus",
"H\tlo yoc,ww\nehers'c lonolep ulkcti?t\n\nI ",
"!eSdnt  oiJ mna difdny uom ni\nenuedcrolhtni.",
"!uHrr yiJ mna difdnm \nynuedwrae.r..htre'e s ",
"!nIt ehs loidre..,.T eh yra eht\neasddse thcc",
"tAe sa,es loidre..\n.oY'uert ehs roirse tolko",
"oDo  fht eiJmm\nyerembmre ,em ?tIi \ns.I.. ,n",
"\neH yiJmm,y\n erembmrem ?e\n\ntIs'm .e..nSto",
"Wklo tn oht eubttnot\n ortgieg rnae evtn ",
"Wklo tn oht eubttnot\n ortgieg rnae evtn ",
"eRrpsene trfmoJ\nmiym !aGgntsrea\noh!yw ro kn",
"aWct huo tiJmm!yv\nlialnia oh!y\n\nrpse sht e",
"Wpi ,udirgno\neparitnoi  nht\neek yfoC  ",
"Wpi ,udirgno\neparitnoi  nht\neek yfoC  ",
"Wpib  yrpseisgnC\nd-wo nubttno ",
"Wpib  yrpseisgnC\nd-wo nubttno ",
"\nuP tifera  toyrus\nna dpserdareb \nyamniatn",
"iFery uo rlbsaet rybh\nloidgnd wo nt\nehz b-t",
"hT eolgnrey uoh lo\ndodnwt eha b tuot\nnht ei",
"!sU eht eehilc-io\nlocdncuot,rf irne!dw\nro k",
"U eehilh-ae,db\nduyd\n!rpse s aubttnot iwec ",
"o,ho ho ,rM .ePvayl ",
"o,ho ho ,rM .ePvayl ",
"Fdieg saLnuhcde ",
"Fdieg saLnuhcde ",
"\nsu tigevh mit ehp\neieco  fapep!r\t\nO\n!K ",
"\nsu tigevh mit ehp\neieco  fapep!r\t\nO\n!K ",
"eH,yw ehera ert eho drre?sI\nt ohguthy uow re",
"eMtem  etat ehg taset  oht\neoc wQHi  n03s ce",
"hWre eewery uo ? Ihtuohg teht\nah tiwhsdet  o",
"hWre eewery uo\n? Ihtuohg toy uawtndet  oehpl",
"aClly uo ,abis coctnniousus\nrcweJ mi ,oyrub ",
"oCemb ca kna des eemw\neh noy uahevf uodn\n l",
"\n Imap puypo  fePet,ry uo\nrrfeidnb teet rna",
"aEtrwhro miJ.m..\n?sIt ah toy.u..\n?\t\nhU..E",
"aTekt ih saeet rna dogy uo..\n.of rht eoldro ",
"sW\nle loden ,hcsoneo en\n.T\nka ehtsiu ddrea",
"\n Imat ehm neat lehtas uaec\n!amync neutirse",
"ewclmo eotm  yhcmaeb,rm\nsyitac lno.eI\na  mh",
"eG ehtnask..rMS puree-ogy\nuov' eebnea b gih ",
"Aistsnaec ,mirpsinodeI s itll\n! ",
"Aistsnaec ,mirpsinodeI s itll\n! ",
"eRlayl ,htyea ert ehk ni gfot\nehc teirloni,i",
"eHpl..h.le pem\n!oW,wa w ro musephrre\nohtniy",
".eHll oJE . Iesmet  oahevh\ndaa  nlaelgrcir a",
"I melraingnt  osu enao\nppsobaelt uhbm ",
"I melraingnt  osu enao\nppsobaelt uhbm ",
".eHll oJE . Iesmet  oahevg\nornwa h na dtscii",
"I melraingnt  oes enia\nonhtred mineisno ",
"I melraingnt  oes enia\nonhtred mineisno ",
"yMm mua ksdem  eott ahkny\nuo .yBt ehw ya ,id",
"?eHll oJE .'Ievg toa t\nihdre ey .oClo- i nst",
"oY'uevf uodnm  yiw!gH\nre'e snau ddre ",
"oY'uevf uodnm  yiw!gH\nre'e snau ddre ",
"aHevy uos ee nymw gi\n? Ihtni k arcbat ei dti",
"Tnaskf rof niidgnm \nyafimyl .aHeva r wera ",
"Tnaskf rof niidgnm \nyafimyl .aHeva r wera ",
"d'I mimssni gujtso enm\nro efom  yiksd- f ni ",
"oY'uevf uodno eno \nfyma uqtacis uqrist- n wo",
"\nle pemf ni dym3 c ihdler.n ",
"\nle pemf ni dym3 c ihdler.n ",
"oCgnarutalitno!sT eh yra\neuqlaficitaoisno  f",
"oCgnarutalitno!sY\nuo rusephrre orcdeneitla ",
"!hTyea ern toI a  mtsargn,et ah\nnhwtaw ti ht",
"N\ntob daa  tla,lM siet riJ!m\n\noSrr yotp tu",
"eHll?oH leol ?oB?bO \nhosrr y Iumtsh va eht\n",
"eWery uoi dnee!d!?T ehw le\nlessew ehhtrey uo",
"uCttni gtia b tic olest eher\n,ewer'n toy?u\n",
"!.O.k .oNb da ,ub toy una\nymAreci aactpia,ni",
"KO .oN tab,db\ntuy uor' eonC paatniA emirac ,",
"eHll?oW ah tahppnedet \nooy?uI d not'l ki eaw",
".H\tleol ?pSae kbauo tiJ mfot ehb\nsacic noit",
"H\tleol\n?aEtrwhro miJ mpsaeikgn\n.oH wimhg t",
"hAE rahtowmrJ mi ,tal sa.tN\nwoI c naa evgn\n",
"\nuGfngitht doyaa  tiHhgN oo.nE\nevyrno eewcl",
"sel-eab-p-aod-oob ",
"sel-eab-p-aod-oob ",
"B\nirllaitn .hTnaskJ mi\n. ",
"B\nirllaitn .hTnaskJ mi\n. ",
"T erpiaesi !sS\nyat  oemt ah toy uahevt ehk ",
"Piaesb !eT\nle lemy uov' eog tht eeksy..\n. ",
"T erGnainsea err\nboibgnt ehB na.k ",
"T erGnainsea err\nboibgnt ehB na.k ",
"ohesv oieltnv riutlav\nlialni savinhsdea agni",
"hT erGnainsea erj su tentxd\noo rnim  yfoifec",
"W\nah tra eoy uodni?g\t\nrE..C ahisgna g na g",
"T\nehG arnnei sra enit ehS lano\n. ",
"T\nehG arnnei sra enit ehS lano\n. ",
"hOt ahkny uo\n.uQci,kg vi eemt ehk ye.s..\n\n",
"T erGnainsea era \ntht eeGenar ltSro\ne ",
"T erGnainsea era \ntht eeGenar ltSro\ne ",
"D\ndiy uog tet ehk ye?s\t\nrEa mlso.tI\nh dat",
"\nofmrf roo nimtne trfmoh re ena\ndrptoce toy",
"g temo tuo  fehera\ndnr seuc eymb lasl\n! ",
"g temo tuo  fehera\ndnr seuc eymb lasl\n! ",
" Imat ehh ae dfot ehp lociei\nsfot ih sicyt ,",
"s\nnoyn ,oy uogtt aehplm !e\n\n'I mht ehsrefi",
"hT eilhgitgnu  pewpanow ti\nhiferc moopentn s",
"Mbmre snoylF\nnuykf riaemrr qeiuer!d ",
"Mbmre snoylF\nnuykf riaemrr qeiuer!d ",
"vEneo htres mo eaWtt?sJ ha\n,olevo  fht eoctn",
"W\tle ltis'l uo,dB\ntui  toclu debl uoed.rJ\n",
"lAawsyt ooc la,mp tui  numhct \noht eot,pt eh",
"S\titllt ooq iute\n,rcna ktiu ,pt\nehk dis'd ",
"\neH,yt eha ris'c ertaruseo \nfahib,tb tui  s",
"H\tye ,rgooyvt nuse\n,uB ttis'a b tiq iutei  ",
"\neWclmole yiwhtt ehc yrtp .hWli\neoy ura eeh",
"eWclmo eott ehc yrtp\n.hWli eoy'uerh re,eW\ny",
"Mekm  een wrfmoh re!e\n\n ",
"Mekm  een wrfmoh re!e\n\n ",
"\ntem  euo tfoh re!e ",
"\ntem  euo tfoh re!e ",
"\nye ,tis't kane\n.\n\nhO ,tis'y uo\n.\n\tW ",
"eH,yi  tsit kane .hA ,tii \nsoy,uy uow re eym",
"H\nye ,tIs't kane\n.O\n,hi 't soy,uH\nva eoy ",
"nhOd ae.rI h va eolts ",
"nhOd ae.rI h va eolts ",
"Dlpyot ehh deegohsg!! ",
"Dlpyot ehh deegohsg!! ",
"! ImaP ysrcwoa dnI w li\nledtsor yoy,uE rahto",
"tIi  sitemt ehert ohes ,hwci\nhnuedlrni eymo ",
"tIs't misel ki ehtse\nehttar meni demo  fymo ",
"T eboejtcviseh va eon ttsurkca\nlli \nn ",
"T eboejtcviseh va eon ttsurkca\nlli \nn ",
"Y uidndt'h tia llt eht raegst ",
"Y uidndt'h tia llt eht raegst ",
"INHG!TN GITH !INHG!TI S YA S\n2IMUNET SOTE EV",
"N !oN !oN ! IASDI2 M NITUSE!! ",
"N !oN !oN ! IASDI2 M NITUSE!! ",
"Lna.. .R\ngelurayl..\n.oMooevo tuised ",
"Lna.. .R\ngelurayl..\n.oMooevo tuised ",
"fIy uoR CEVOREy uof si htsra\ntoy utsurkct eh",
".O.Ky uow rohtelssp eieco\n fifhsb-ia,ty\nuob",
"mIebicel ,imssdey uoa t raeg!tT\neh yenev rel",
"oFlo ,oy uimssdea t raeg!ty\nuol' lenev relva",
"hTyei snrtcu tht eogdos\nloidre!sT  ooctnor l",
"oY'uerd iogng oo dosdlei!rT\nyrt ehn xe testc",
"OM-OISILIN !hwtah re eody uof\nro?mI  tsit eh",
"M\toos-lini!iw\nah tra eoy uodni geher\n?\t\n",
".iWer ,oy uameda g ertas reivecw\nti hhcciek-",
"oS,ny uov' eodena g ertas\nreivect  ohcciek-n",
"!rpcoru enot ehr oo fna drpcoru\neoy uehert  ",
"eg tnot ehr oo\nfna deg temo tuath re!e\t\n\n",
"\nN\tton .o.. ,hT esaeptco ruf\neeel rugga,ep",
"eHll,os noyn\n!oy'u debttreg teg iogn\n,tIs'p",
"T\tehp ia nra eymb se trfeidn ,sat\nreor rsim",
"\noY'uevr teruen\ndna doy'uevb orguth\n ht er",
"hWre eehi  sht eocolen?lA erw \ne aisngficina",
"\n.\n..bauo ton!w\n\nxEecllne,tt ah't s aabel",
"hTyee tnrei  nemna,st eh yifdnt\nehG nerelaa ",
"R\ngith ,el't sogo ev rht elpna\n!Y\nuog  oni",
"nIen raptrc moopes dfoB ESI m\nsu thcracaetir",
"\noY uamedi !tS\nss,hT eh yod'n tnkwoI m'h re",
". Iacemo  nht eub\nsrfmob aritlsva!a\n\n\t\nh",
"TIA ELTR!Si  tsiw ti hht\netaettnoi,na p irtn",
"awnrni!gt\nih ssia w lildfi\nerptoceitnoz no.",
"tIy uoa eltr !hT easemm voni\ngasdn .oFtotspe",
"Wnrni!gV\nre yuQciskna.dT\nerdac rafeluyl ",
"Wnrni!gV\nre yuQciskna.dT\nerdac rafeluyl ",
"Ta nnuocn eomibels na.d\n\n ",
"Ta nnuocn eomibels na.d\n\n ",
"Wct huo tiJ!mT\nehers'q iukcasdna obtu\n! ",
"Wct huo tiJ!mT\nehers'q iukcasdna obtu\n! ",
"ht eHO ,oy uac nrtae t aabybC\nrosp!eh re eos",
"ho ,abyby\nuok on woh wott ertaa c rosp!e\n\n",
"id doy uifdni  tohewev?rI s eey\nuot  orcaeut",
"h\nva eoy uofnu dtiy te\n?\t\nY\nse\n\n\n\trG",
"tIi  seher- d dao  fht eoleva\nhceiev dtit  o",
"eHerl ei s -oLevD daydH\n eercaeh ds1 tlpca,e",
"tIi  seher- t ehp ra tfoL\nbaleela  sht elpca",
" tekpet ehp ca.e ",
" tekpet ehp ca.e ",
"tIi  seher- m suciD va efoD\nsioch sac uahg t",
"eHerl ei s -iDcs oaDevh\n eercaeh dr3 dlpca,e",
"id doy utsli lifdni ?tO tbia\nnhtnei  ndaidit",
"\nh\nva eoy uofnu dtiy te\n?\t\nN\n\no\t\nT\n",
"nOw ihhcw yao  fht ehsnini\ngohrrroI h va eac",
"!eH yrgooyvb ba.y..Y\nuom su tebt ehw ro\nmve",
"hTnet  ooctnnieu !erlayl ,atkst\nah teramnih ",
"uHrrhaf rot ehw ro mehorn\nwoI a  mrfeet \nos",
"Gaeet raptro  fhtyeh sat eh\nyti ",
"Gaeet raptro  fhtyeh sat eh\nyti ",
"Y'uevg tom so tfot eh\nm ",
"Y'uevg tom so tfot eh\nm ",
"Semh va eebug,nb tuI c naf ee\nldouo romer\n. ",
"Semh va eebug,nb tuI c naf ee\nldouo romer\n. ",
"Y uog tosem ,ub t Iac\nnmsle lomer\n. ",
"Y uog tosem ,ub t Iac\nnmsle lomer\n. ",
"tig te sht eustsneatitnot ehera\ndni  tifinhs",
"eg tabkco tut ehera\ndnf nisi hfo fhtso\nehcc",
"!ht enUvireisytp\norefssrom-noek-ynio drret\n",
"hw'o shtre?ed\nnot'h ru tem\n!\t\niFsr,ty uot",
"OBGN !oTs oh wott eho tuised\n!eBvarea pporix",
"OBGN\n!aWct huo!tB aeev rbauo!t\n\niH tht ews",
"OBGN.!..W RAINGN !hTre esiv\nmaiper sotb sa e",
"B\nNO!G.. .AWNRNI!G\n\nhTre'e snud-ae doplurt",
"OBGN !eH yijmm,yw ti hht eamon\nrfot ehm noek",
"\nOBGN !eH yiJmm,yW\nleocemt  ooMknyeM naro\n",
"aMnietancn eacnntod  oonm ro\nehtsii snrtmune",
"aC'n.t..atkl..a.ynomer\n!pAlpaicn.e..rcsuihgn",
"hTsiw roskatitnoi  srfmot ehs\nrtnaegp orejtc",
"\newclmo eott ehm daohsu.ee\nrahtowmrj mi\n.h",
"hOy uoa era c nayd ,fiI f yl\n,httaI w li lac",
"ea s ewteei\n,fiI f yl ,'Illc tahct ehe cnro!",
"\nhT ecSer wiwhtuo tia mogse\n!eMnah aeidgno ",
"GW ro!mF\nni dymb aeev rehda\n! ",
"GW ro!mF\nni dymb aeev rehda\n! ",
" Imat ehc moupet rabkcpuo \nfabor neBvareF-ro"
};

function correctString(input_string)
	if string.len(input_string) % 2 == 1 then
		pre_format_string = input_string.." ";
	else
		pre_format_string = input_string;
	end
	swap_count = string.len(pre_format_string) / 2;
	modified_string = ""
	for i=1, swap_count do
		char_1 = string.sub(pre_format_string, (2 * i) - 1, (2 * i) - 1);
		char_2 = string.sub(pre_format_string, 2 * i, 2 * i);
		modified_string = modified_string..char_2..char_1;
	end
	print(modified_string);
end

function correctEverything()
	for i = 1, #strings do
		correctString(strings[i]);
	end
end